name: grayscale_filter
description: A package to apply grayscale filters to images with customizable intensity.
version: 0.0.1
repository: https://github.com/lucas-goldner/grayscale_filter/
homepage: https://github.com/lucas-goldner/grayscale_filter/

environment:
  sdk: ^3.4.0-0

dependencies:
  args: ^2.4.2
  image: ^4.1.7

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
